### ISSUE TITLE
Dolphin file manager can't access webdavs (https) server

### ISSUE THREAD

**Issue by andrew-ysk** [ipfs/integrations#25]
Hii,

I couldn't find any soln on the web anywhere for months already. Hence have to come to seek for help.. hopefully someone able to help me. 

Dolphin and winscp (windows os app) was able to connect to a company  webdavs (https) server wonderfully, connection and copy files are tremendously fast, very satisfying. 
but the company updated the server so that it takes user agent from client before allowing connection. 
So now, dolphin is no longer able to access to the webdavs, however winscp still able to access the webdavs just fine. 

Is there anyway to config user agent on dolphin side ?  it is so sad that dolphin can't connect to webdavs that require client to provide user agent . 

I am running manjaro kde plasma.  
Kernel: 5.15.146-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.10 Distro: Manjaro Linux
Dolphin file manager Version         : 23.08.4-1

Your favorable reply will be very much appreciated. 

Thanks
Andrew
Andrew_ysk@yahoo.com

**Comment by markg85** [comment]
Hi Andrew,

This is not the place for asking Dolphin support.

You should probably ask here https://discuss.kde.org/
or perhaps in one of their irc channels https://userbase.kde.org/IRC_Channels
